### ISSUE TITLE
Wrong link to image causes 500 error

### ISSUE THREAD

**Issue by KrzysztofMadejski** [KohoVolit/api.parldata.eu#2]
Sending www.kuvendikosoves.orgcommon/images/mp/ldk_agim_krasniqi.jpg
instead of www.kuvendikosoves.org/common/images/mp/ldk_agim_krasniqi.jpg

Gives 500 internal server error.
Instead validation error should be returned.

```
Array
(
    [id] => mp_131_AgimKrasniqi
    [name] => Agim Krasniqi
    [given_name] => Agim
    [additional_name] => Krasniqi
    [image] => http://www.kuvendikosoves.orgcommon/images/mp/ldk_agim_krasniqi.jpg
    [birth_date] => 1956-05-17
    [sources] => Array
        (
            [0] => Array
                (
                    [url] => http://www.kuvendikosoves.org?cid=1,158,131&secid=102&legid=1
                )

        )

)

{"id":"mp_131_AgimKrasniqi","name":"Agim Krasniqi","given_name":"Agim","additional_name":"Krasniqi","image":"http:\/\/www.kuvendikosoves.orgcommon\/images\/mp\/ldk_agim_krasniqi.jpg","birth_date":"1956-05-17","sources":[{"url":"http:\/\/www.kuvendikosoves.org?cid=1,158,131&secid=102&legid=1"}]}

HttpSocketResponse Object
(
    [body] => 



Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.
```

**Comment by girogiro** [comment]
Should be fixed now. The error occurred when trying to download and mirror a file from nonexistent URL. Nonexistent URLs in mirrored fields (`Person.image` and `Organization.image`) are left unchanged now.

Generally, URL fields are not validated for syntax correctness, because virtually everything is a valid URL according to RFC 3986. Nor they are validated for existence - it would require an additional HTTP request to the remote URL for almost every inserted entity (think of `sources.url` field in millions of votes and speeches). Also the URL may be correct but temporary down or going to be populated in the future.

**Comment by KrzysztofMadejski** [comment]
I was imagining that you've created a queue where all urls go and they are asynchronously downloaded. 
Sometimes a site can be down, nevertheless those external sources could be mirrored finally. 

-------- Oryginalna wiadomość --------
Od: Jaroslav Semančík <notifications@github.com> 
Data:2015.02.05  21:05  (GMT+01:00) 
Do: "KohoVolit/api.parldata.eu" <api.parldata.eu@noreply.github.com> 
DW: Krzysiek Madejski <krzysztof@madejscy.pl> 
Temat: Re: [api.parldata.eu] Wrong link to image causes 500 error (#2) 

Should be fixed now. The error occurred when trying to download and mirror a file from nonexistent URL. Nonexistent URLs in mirrored fields (Person.image and Organization.image) are left unchanged now.

Generally, URL fields are not validated for syntax correctness, because virtually everything is a valid URL according to RFC 3986. Nor they are validated for existence - it would require an additional HTTP request to the remote URL for almost every inserted entity (think of sources.url field in millions of votes and speeches). Also the URL may be correct but temporary down or going to be populated in the future.
